#######################################################################
# SConscript for remote-xlib winsys

Import('*')

if env['platform'] == 'linux' \
        and 'mesa' in env['statetrackers'] \
        and 'remote' in env['drivers'] \
        and not env['dri']:

    env = env.Clone()

    env.Append(CPPPATH = [
	'.',
        '#/src/mesa',
        '#/src/mesa/main',
        '../../drivers/remote',
	'/usr/include/X11',
	'/usr/include/X11/extensions'
    ])
   
    env.Append(CFLAGS = [ '-std=c99' ])

    sources = [
        'glxapi.c',
        'fakeglx.c',
        'xfonts.c',
        'xm_api.c',
        'tr_winsys.c',
	'ext.c'
    ]
        
    drivers = [
        remote,
    ]
    
    # TODO: write a wrapper function http://www.scons.org/wiki/WrapperFunctions
    libgl = env.SharedLibrary(
        target ='GL',
        source = sources,
        LIBS = glapi + mesa + drivers + auxiliaries + env['LIBS'],
    )

    env.InstallSharedLibrary(libgl, version=(1, 5))
    