
#include "remote_messages.h"

char* optotext(unsigned opcode) {

  switch(opcode) {

	case REMREQ_SET_EDGEFLAGS:
	
		return "REMREQ_SET_EDGEFLAGS";

	case REMREQ_DRAW_ARRAYS:
	
		return "REMREQ_DRAW_ARRAYS";

	case REMREP_DRAW_ARRAYS:
	
		return "REMREP_DRAW_ARRAYS";

	case REMREQ_DRAW_ELEMENTS:
	
		return "REMREQ_DRAW_ELEMENTS";

	case REMREP_DRAW_ELEMENTS:
	
		return "REMREP_DRAW_ELEMENTS";

	case REMREQ_DRAW_RANGE_ELEMENTS:
	
		return "REMREQ_DRAW_RANGE_ELEMENTS";

	case REMREP_DRAW_RANGE_ELEMENTS:
	
		return "REMREP_DRAW_RANGE_ELEMENTS";

	case REMREQ_CREATE_QUERY:
	
		return "REMREQ_CREATE_QUERY";

	case REMREQ_DESTROY_QUERY:
	
		return "REMREQ_DESTROY_QUERY";

	case REMREQ_BEGIN_QUERY:
	
		return "REMREQ_BEGIN_QUERY";

	case REMREQ_END_QUERY:
	
		return "REMREQ_END_QUERY";

	case REMREQ_GET_QUERY_RESULT:
	
		return "REMREQ_GET_QUERY_RESULT";

	case REMREP_GET_QUERY_RESULT:
	
		return "REMREP_GET_QUERY_RESULT";

	case REMREQ_CREATE_BLEND_STATE:
	
		return "REMREQ_CREATE_BLEND_STATE";

	case REMREQ_BIND_BLEND_STATE:
	
		return "REMREQ_BIND_BLEND_STATE";

	case REMREQ_DELETE_BLEND_STATE:
	
		return "REMREQ_DELETE_BLEND_STATE";

	case REMREQ_CREATE_SAMPLER_STATE:
	
		return "REMREQ_CREATE_SAMPLER_STATE";

	case REMREQ_BIND_SAMPLER_STATE:
	
		return "REMREQ_BIND_SAMPLER_STATE";

	case REMREQ_DELETE_SAMPLER_STATE:
	
		return "REMREQ_DELETE_SAMPLER_STATE";

	case REMREQ_CREATE_RAST_STATE:
	
		return "REMREQ_CREATE_RAST_STATE";

	case REMREQ_BIND_RAST_STATE:
	
		return "REMREQ_BIND_RAST_STATE";

	case REMREQ_DELETE_RAST_STATE:
	
		return "REMREQ_DELETE_RAST_STATE";

	case REMREQ_CREATE_DSA_STATE:
	
		return "REMREQ_CREATE_DSA_STATE";

	case REMREQ_BIND_DSA_STATE:
	
		return "REMREQ_BIND_DSA_STATE";

	case REMREQ_DELETE_DSA_STATE:
	
		return "REMREQ_DELETE_DSA_STATE";

	case REMREQ_CREATE_FS_STATE:
	
		return "REMREQ_CREATE_FS_STATE";

	case REMREQ_BIND_FS_STATE:
	
		return "REMREQ_BIND_FS_STATE";

	case REMREQ_DELETE_FS_STATE:
	
		return "REMREQ_DELETE_FS_STATE";

	case REMREQ_CREATE_VS_STATE:
	
		return "REMREQ_CREATE_VS_STATE";

	case REMREQ_BIND_VS_STATE:
	
		return "REMREQ_BIND_VS_STATE";

	case REMREQ_DELETE_VS_STATE:
	
		return "REMREQ_DELETE_VS_STATE";

	case REMREQ_SET_BLEND_COLOR:
	
		return "REMREQ_SET_BLEND_COLOR";

	case REMREQ_SET_CLIP_STATE:
	
		return "REMREQ_SET_CLIP_STATE";

	case REMREQ_SET_POLYGON_STIPPLE:
	
		return "REMREQ_SET_POLYGON_STIPPLE";

	case REMREQ_SET_SCISSOR_STATE:
	
		return "REMREQ_SET_SCISSOR_STATE";

	case REMREQ_SET_VIEWPORT_STATE:
	
		return "REMREQ_SET_VIEWPORT_STATE";

	case REMREQ_SET_CONSTANT_BUFFER:
	
		return "REMREQ_SET_CONSTANT_BUFFER";

	case REMREQ_SET_FRAMEBUFFER_STATE:
	
		return "REMREQ_SET_FRAMEBUFFER_STATE";

	case REMREQ_SET_SAMPLER_TEXTURES:
	
		return "REMREQ_SET_SAMPLER_TEXTURES";

	case REMREQ_SET_VERTEX_BUFFERS:
	
		return "REMREQ_SET_VERTEX_BUFFERS";

	case REMREQ_SET_VERTEX_ELEMENTS:
	
		return "REMREQ_SET_VERTEX_ELEMENTS";

	case REMREQ_SURFACE_COPY:
	
		return "REMREQ_SURFACE_COPY";

	case REMREQ_SURFACE_FILL:
	
		return "REMREQ_SURFACE_FILL";

	case REMREQ_CLEAR:
	
		return "REMREQ_CLEAR";

	case REMREQ_FLUSH:
	
		return "REMREQ_FLUSH";

	case REMREQ_DESTROY_CONTEXT:
	
		return "REMREQ_DESTROY_CONTEXT";

	case REMREQ_CREATE_CONTEXT:
	
		return "REMREQ_CREATE_CONTEXT";

	case REMREP_CREATE_CONTEXT:
	
		return "REMREP_CREATE_CONTEXT";

	case REMREQ_GET_PARAM:
	
		return "REMREQ_GET_PARAM";

	case REMREP_GET_PARAM:
	
		return "REMREP_GET_PARAM";

	case REMREQ_GET_PARAMF:
	
		return "REMREQ_GET_PARAMF";

	case REMREP_GET_PARAMF:
	
		return "REMREP_GET_PARAMF";

	case REMREQ_IS_FORMAT_SUPPORTED:
	
		return "REMREQ_IS_FORMAT_SUPPORTED";

	case REMREP_IS_FORMAT_SUPPORTED:
	
		return "REMREP_IS_FORMAT_SUPPORTED";

	case REMREQ_TEXTURE_CREATE:
	
		return "REMREQ_TEXTURE_CREATE";

	case REMREP_TEXTURE_CREATE:
	
		return "REMREP_TEXTURE_CREATE";

	case REMREQ_TEXTURE_BLANKET:
	
		return "REMREQ_TEXTURE_BLANKET";

	case REMREP_TEXTURE_BLANKET:
	
		return "REMREP_TEXTURE_BLANKET";

	case REMREQ_TEXTURE_RELEASE:
	
		return "REMREQ_TEXTURE_RELEASE";

	case REMREQ_GET_TEX_SURFACE:
	
		return "REMREQ_GET_TEX_SURFACE";

	case REMREP_GET_TEX_SURFACE:
	
		return "REMREP_GET_TEX_SURFACE";

	case REMREQ_TEX_SURFACE_RELEASE:
	
		return "REMREQ_TEX_SURFACE_RELEASE";

		/*	case REMREQ_SURFACE_MAP:
	
		return "REMREQ_SURFACE_MAP";

	case REMREP_SURFACE_MAP:
	
		return "REMREP_SURFACE_MAP";

	case REMREQ_SURFACE_UNMAP:
	
	return "REMREQ_SURFACE_UNMAP";*/

	case REMREQ_CREATE_SCREEN:
	
		return "REMREQ_CREATE_SCREEN";

	case REMREP_CREATE_SCREEN:
	
		return "REMREP_CREATE_SCREEN";

	case REMREQ_FLUSH_FRONTBUFFER:
	
		return "REMREQ_FLUSH_FRONTBUFFER";

	case REMREQ_BUFFER_CREATE:
	
		return "REMREQ_BUFFER_CREATE";

	case REMREQ_USER_BUFFER_CREATE:
	
		return "REMREQ_USER_BUFFER_CREATE";

	case REMREQ_USER_BUFFER_UPDATE:
	
		return "REMREQ_USER_BUFFER_UPDATE";

		/*	case REMREQ_BUFFER_MAP:
	
		return "REMREQ_BUFFER_MAP";

	case REMREP_BUFFER_MAP:
	
		return "REMREP_BUFFER_MAP";

	case REMREQ_BUFFER_UNMAP:
	
	return "REMREQ_BUFFER_UNMAP";*/

  case REMREQ_BUFFER_GET_DATA:
    return "REMREQ_BUFFER_GET_DATA";

  case REMREP_BUFFER_GET_DATA:
    return "REMREP_BUFFER_GET_DATA";

  case REMREQ_BUFFER_SET_DATA:
    return "REMREQ_BUFFER_SET_DATA";

  case REMREP_BUFFER_SET_DATA:
    return "REMREP_BUFFER_SET_DATA";

	case REMREQ_BUFFER_DESTROY:
	
		return "REMREQ_BUFFER_DESTROY";

	case REMREQ_SWAP_BUFFERS:
	
		return "REMREQ_SWAP_BUFFERS";



 default:
   return "*** UNRECOGNISED OPCODE ***";
  }
}

